### ISSUE TITLE
RuleReactor.run() TypeError: "callback" argument must be a function

### ISSUE THREAD

**Issue by slmmm** [anywhichway/rule-reactor#1]
An error is being thrown by calls to RuleReactor.run() due to setTimeout use of "run()" as the callback.

I have created a very basic Server that responds to a GET request by running a simple test of multiple rules and actions on an object (code and results below).

**Am I using RuleReactor.run() incorrectly, or is this a bug?**

**Basic Server:**
[server.txt](https://github.com/anywhichway/rule-reactor/files/312460/server.txt)

**Returned Results with stacktrace:**
`test1 fired: {"value":"tester"}
**TypeError: "callback" argument must be a function**
    at exports.setTimeout (timers.js:314:11)
    at RuleReactor.run (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\rule-reactor\index.js:1211:3)
    at C:\Users\slmmm\Documents\Projects\RErulereactor\server.js:84:16
    at Layer.handle [as handle_request] (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\index.js:277:22
    at Function.process_params (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Users\slmmm\Documents\Projects\RErulereactor\node_modules\express\lib\router\index.js:271:10)
test2 fired: {"value":"tester"}`

**For now, to resolve my issue**, I've updated rule-reactor/index.js (line 1211) by replacing "run()" with "run" as such:
`setTimeout(run,0);`

**Comment by anywhichway** [comment]
Investigating. Thanks for the report.

**Comment by anywhichway** [comment]
Fixed, unit tests updated, pushed to npmjs.org
