### ISSUE TITLE
asserting an object before any rule has the object's type as domain causes an error

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#15]
Test case:
```
> cat >issue12.js
var RuleReactor = require("rule-reactor");
var reactor = new RuleReactor();
function Instance(i) { Object.assign(this, i); }
reactor.assert(new Instance({a:1}));
> node issue12.js
/big/home/src/rule-reactor/index.js:864
                                Object.keys(instance.activeKeys).forEach(function(key) {
                                       ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at /big/home/src/rule-reactor/index.js:864:12
    at Array.forEach (native)
    at RuleReactor.assert (/big/home/src/rule-reactor/index.js:835:13)
    at Object.<anonymous> (/big/home/src/rule-reactor/examples/issue12.js:4:9)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
```
The bug is that instance.activeKeys is only created when a rule has `Instance` as domain, thus `Object.keys(instance.activeKeys)` fails. The work-around is to ensure that rules are defined before any fact is asserted, but this can be tricky when rules are created dynamically, for example to create stages.

**Comment by tve** [comment]
Quick fix:
```
@@ -851,16 +851,16 @@ var uuid = require("uuid");
                                instance.constructor.instances = (instance.constructor.instances ? instance.constructor.instances : []);
                                instance.constructor.instances.push(instance);
                                instance.constructor.index = (instance.constructor.index ? instance.constructor.index : {});
+                               var cons = instance.constructor;
+                               cons.prototype.activeKeys = (cons.prototype.activeKeys ? cons.prototype.activeKeys : {});
                                indexObject(instance.constructor.index,instance);
                                // patch any keys on instance or those identified as active while compiling
                                var keys = Object.keys(instance);
-                               if(instance.activeKeys) {
                                Object.keys(instance.activeKeys).forEach(function(key) {
                                        if(keys.indexOf(key)===-1) {
                                                keys.push(key);
                                        }
                                });
-                               }
                                Object.keys(instance.activeKeys).forEach(function(key) {
                                        function rrget() {
                                                return rrget.value;
```

**Comment by anywhichway** [comment]
After reviewing you code we also identified a bug that would result in some rules not firing in edge cases when data was asserted before the rules were created. We have applied a fix at a "higher level" in the code as a result. v0.1.3 has been pushed to GitHub but not npm. See test/issue15.html. Let me know when you have verified, or just close this issue.
