### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#16]
The following test:
```
var RuleReactor = require("./index");
var reactor = new RuleReactor();
function Instance(i) { Object.assign(this, i); }
function Image(i) { Object.assign(this, i); }

reactor.createRule("hello", 0, {i: Instance},
  function(i) { return i.a == 1; },
  function(i) {
    console.log("asserting & setting");
    var im = new Image({a: 0});
    reactor.assert(im);
    im.a = i.a+1;
  }
);

reactor.createRule("stop", -100, {},
  function() { return true; },
  function() { reactor.stop(); }
);

reactor.assert(new Instance({a:1}));

reactor.run(Infinity, false, null);
```
results in:
```
> node issue.js
asserting & setting
/big/home/src/rule-reactor/index.js:872
                                                        Object.keys(instance.rules).forEach(function(rulename) {
                                                               ^

TypeError: Cannot convert undefined or null to object
    at Image.rrset [as a] (/big/home/src/rule-reactor/index.js:872:15)
    at Rule.action (/big/home/src/rule-reactor/issue.js:12:10)
    at Rule.rule.compiledAction (/big/home/src/rule-reactor/index.js:379:17)
    at Rule.fire (/big/home/src/rule-reactor/index.js:551:8)
    at Activation.execute (/big/home/src/rule-reactor/index.js:448:12)
    at Timeout.run [as _onTimeout] (/big/home/src/rule-reactor/index.js:1163:36)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by anywhichway** [comment]
Researching...

**Comment by anywhichway** [comment]
@tve We have pushed a fixed version to GitHub (but not published to NPM yet). Please verify and close.

Happy Holidays and a productive New Year!

**Comment by tve** [comment]
Thanks!
