### ISSUE TITLE
"Maximum call stack size exceeded" when calling assert

### ISSUE THREAD

**Issue by jddahl** [anywhichway/rule-reactor#17]
Hi,

I am trying to set-up an application using rule-reactor engine.

It works well, executing rules on sets of facts that I provide, but sometimes, it seems to reach a stack limit as I put a bit more facts than during my first tests. (about 10 facts corresponding to an array of similar objects having 13 properties each).
I would say this is not a huge set, so I guess the problem is not related to the quantity of facts, but something else.

That doesn't occur systematically, but frequently, notably, if I call the rules engine several times with different sets of facts.

I am quite new to node.js, so it is possible that I don't use the library the way it should be.
Please let me know if you need some other pieces of information.

Thanks for your hints.

The Error Stack that I get is this one:

    Error RangeError: Maximum call stack size exceeded
        at updateIndex (/usr/src/node_modules/rule-reactor/index.js:679:21)
        at GenericEntity.rrset [as tenant] (/usr/src/node_modules/rule-reactor/index.js:865:8)
        at eval (eval at <anonymous> (/usr/src/node_modules/rule-reactor/index.js:1:0), <anonymous>:4:29)
        at Rule.eval (eval at <anonymous> (/usr/src/node_modules/rule-reactor/index.js:1:0), <anonymous>:5:12)
        at /usr/src/node_modules/rule-reactor/index.js:597:26
        at Array.every (native)
        at test (/usr/src/node_modules/rule-reactor/index.js:596:33)
        at dive (/usr/src/node_modules/rule-reactor/index.js:165:6)
        at dive (/usr/src/node_modules/rule-reactor/index.js:171:6)
        at CXProduct.forEach1 (/usr/src/node_modules/rule-reactor/index.js:182:3)
        at /usr/src/node_modules/rule-reactor/index.js:603:17
        at Array.forEach (native)
        at Rule.test (/usr/src/node_modules/rule-reactor/index.js:590:15)
        at /usr/src/node_modules/rule-reactor/index.js:886:16
        at Array.forEach (native)
        at GenericEntity.rrset [as tenant] (/usr/src/node_modules/rule-reactor/index.js:874:37)

**Comment by jddahl** [comment]
Hi,

 I think having found the answer.
Actually, debugging the code, I saw that the rules were evaluated even when calling assert method.
Looking again at my code, I discovered that one of my rules was wrongly spelled with the test condition not having == operator but = instead. I guess this caused an issue in the evaluation of the rule and a subsequent raise in the combination of cases.

**Comment by anywhichway** [comment]
@jddahl glad you were able to resolve and thanks for using rule-reactor.
