### ISSUE TITLE
Syntax Error with exists when pattern matching across multiple instances

### ISSUE THREAD

**Issue by sohzaz** [anywhichway/rule-reactor#28]
Hi,

When attempting to use exists() to pattern match across multiple instances of the same class, the engine throws a syntax error.

The example node code to reproduce the issue:

```javascript
const RuleReactor = require("rule-reactor");
reactor = new RuleReactor()

A = function(val) {
    this.val = val;
}
exists = function () { return reactor.exists.apply(reactor,arguments); }
reactor.assert(new A(1))
reactor.assert(new A(2))
reactor.assert(new A(4))

reactor.createRule('test',0,{a: A},
    function (a) {
        return a.val == 1 && exists({a1:A, a2:A}, {a1:{val: 2}, a2:{val: 4}})
    }, function (a) {
        console.log(a)
        reactor.stop()
    })
reactor.run(Infinity,true,function() {
    console.log('done');
});
````

And its output:

```
undefined:3
})
 ^

SyntaxError: Unexpected token )
    at new Function (<anonymous>)
    at /home/pi/rules_service/node_modules/rule-reactor/index.js:269:19
    at String.replace (<anonymous>)
    at /home/pi/rules_service/node_modules/rule-reactor/index.js:267:19
    at Array.forEach (<anonymous>)
    at compile (/home/pi/rules_service/node_modules/rule-reactor/index.js:266:19)
    at new Rule (/home/pi/rules_service/node_modules/rule-reactor/index.js:517:3)
    at RuleReactor.createRule (/home/pi/rules_service/node_modules/rule-reactor/index.js:1026:25)
    at Object.<anonymous> (/home/pi/rules_service/test.js:14:9)
    at Module._compile (module.js:660:30)
```

As far as I can tell, it seems that the second capture group in the regex at the line 267 doesn't behave properly when trying to pattern match with more than one object.

**Comment by anywhichway** [comment]
@sohzaz I have reviewed our source and determined that exists can't currently support more than one instance the same applies to forall. I will make some attempt to enhance the code this week, but I am not optimistic.
