### ISSUE TITLE
how to structure an http service around rule-reactor

### ISSUE THREAD

**Issue by tve** [anywhichway/rule-reactor#6]
Could you provide a sketch for how you would structure an http service around rule-reactor? Things I'm wondering:

- assume the HTTP interface allows facts to be modified, for example, change the address of a patient, is it best to implement this by updating the appropriate fact object or is it better to retract the entire patient fact and assert a new one? (Assuming that some rules on Patients don't need to fire if just the address changes.)

- how do I run the main loop that accepts HTTP requests and runs rule-reactor? I assume that running rule-reactor with an Infinity parameter after every HTTP request would be too slow. So do I try to dynamically converge on some number of rule firings passed into reactor.run so it runs for a few ms and then relinquishes control so HTTP requests can be accepted?

Apologies for the 'newbie' flavor of the question, I clearly have to dig into the rule-reactor code to understand how things work (and get up on the learning curve of node.js).

**Comment by anywhichway** [comment]
Please look at the README paragraphs at the end of Basic Use and right before Advanced Use. You have two choices:

1) Write a low salience rule that will call stop when there are no more rules to run. Add a function call to the stop rule to send data to the client.
2) Call run with Infinity,true,callback. The callback could send a response to clients.

If you choose option 1, then every time you get an HTTP request that is supposed to modify a reactor, do the modifications (add rules, assert data) and then call run and queue any new requests until reactor stops running.

If you choose option 2, then every time you get an HTTP request that is supposed to modify a reactor, just do the modifications (add rules, assert data). In this case you will probably have to add data to the facts to indicate which client request they are a response to.

**Comment by tve** [comment]
A node.js example would have been awesome. I'm not a node.js whizz and I'm obviously doing something wrong but it's not obvious... I modified the family.html example by removing the mark-up and changed the top to
```
var RuleReactor = require("rule-reactor");
var reactor = new RuleReactor();
```
but that fails with
```
> node family.js
undefined:2
return {person: Person}
                ^

ReferenceError: Person is not defined
    at eval (eval at <anonymous> (/big/home/src/rule-reactor/index.js:285:19), <anonymous>:2:17)
    at /big/home/src/rule-reactor/index.js:285:54
```
using `new RuleReactor({Address:Address, Person:Person})` is no better. Now I'm trying to figure out how to get Person and Address into the global namespace so RuleReactor sees them in its eval...

**Comment by anywhichway** [comment]
See the new example in v0.1.2 examples/async-assertions.html
